#!/usr/bin/env python3
"""
Quick script to generate a few samples from the trained VAE.
"""

import torch
import numpy as np
from pathlib import Path
import sys

# Add project root to path
sys.path.append(str(Path(__file__).parent.parent))

from VAE.Simple_VAE import LGL_VAE
from DataLoader.Chromosome21PDBDataset import Chromosome21PDBDataset
from Utils.Utils import Utils


def main():
    # Configuration
    model_path = "./outputs/trained_vae_model.pt"
    dataset_path = "./Data/chromosome21_aligned.pdb"
    output_dir = "./outputs/Generated_Samples"
    num_samples = 7500
    HIDDEN_DIM = 1024
    LATENT_DIM = 2
    LATENT_VARIANCE = 15.0  # Variance multiplier for latent space sampling (1.0 = standard normal)
    
    # Create output directory
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    # Load dataset to get dimensions
    print("Loading dataset...")
    dataset = Chromosome21PDBDataset(
        pdb_path=dataset_path,
        record_types=("ATOM",),
        center=True,
        scale=1.0
    )
    input_dim = dataset.vector_length
    print(f"Input dimension: {input_dim}")
    
    # Load model
    print("Loading trained model...")
    utils = Utils()
    model = LGL_VAE(hidden_dim=HIDDEN_DIM, latent_dim=LATENT_DIM, input_dim=input_dim)
    model = model.to(utils.device)
    
    checkpoint = torch.load(model_path, map_location=utils.device)
    model.load_state_dict(checkpoint)
    model.eval()
    
    # Generate samples
    print(f"Generating {num_samples} samples...")
    print(f"Using latent variance multiplier: {LATENT_VARIANCE}")
    with torch.no_grad():
        # Sample from latent space with specified variance
        z = torch.randn(num_samples, LATENT_DIM, device=utils.device) * np.sqrt(LATENT_VARIANCE)
        samples = model.decoder(z)
    
    # Convert to PDB format - single file with multiple models
    samples_np = samples.cpu().numpy()
    
    # Create single output PDB file
    output_file = Path(output_dir) / "generated_samples.pdb"
    
    # Write header
    with open(output_file, 'w') as f:
        f.write("HEADER    GENERATED CHROMOSOME STRUCTURES FROM VAE LATENT SPACE\n")
        f.write("REMARK    Each MODEL represents one sampled point from the latent space\n")
        f.write("REMARK    Generated by ChromatinVAE quick sampling script\n")
    
    # Add each sample as a model
    for i, sample in enumerate(samples_np):
        with open(output_file, 'a') as f:  # Append mode
            f.write(f"MODEL        {i+1:4d}\n")
            
            num_atoms = len(sample) // 3
            for j in range(num_atoms):
                x, y, z = sample[j*3:(j+1)*3]
                f.write(f"ATOM  {j+1:5d}  CA  UNK A{j+1:4d}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           C\n")
            
            f.write("ENDMDL\n")
        
        print(f"Added sample {i+1} as MODEL {i+1}")
    
    print(f"\nGenerated {num_samples} samples in single PDB file: {output_file}")
    print("You can view this with PyMOL, VMD, or other molecular viewers!")
    print("Each MODEL in the file represents one sampled structure from the latent space.")


if __name__ == "__main__":
    main()
